### ISSUE TITLE
Waarvoor is er een hidden input die dezelfde naam heeft als de radio buttons

### ISSUE THREAD

**Issue by JeroenHeemskerk** [abdelmounaimn/educom-webshop-basis#11]
Ik kan de volgende regel niet verklaren
https://github.com/abdelmounaimn/educom-webshop-basis/blob/e96ad79529388a2b5bd502e0d09396b092a687a7/contact.php#L87

Kan je uitleggen waarom deze in de code zit. om te zorgen dat er een post waarde is ook als er niets geselecteerd is?

**Comment by abdelmounaimn** [comment]
Ik heb dat gedaan om de client bewust een optie te laten kiezen. Ik dacht dat er automatisch een Radio wordt geselecteerd. Maar toen ik zag dat dat niet zo was heb ik het verwijderd.
